src/Entity/Todo.php
<?php

namespace App\Entity;

use DateTime;
use Doctrine\ORM\Mapping as ORM;

/**
 * @ORM\Entity(repositoryClass="App\Repository\TodoRepository")
 */
class Todo
{
    /**
     * @ORM\Id
     * @ORM\GeneratedValue
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @var string
     * @ORM\Column(name="name", type="string")
     */
    private $name = "";

    /**
     * @var string
     * @ORM\Column(name="category", type="string")
     */
    private $category = "";

    /**
     * @var string
     * @ORM\Column(name="description", type="string")
     */
    private $description = "";

    /**
     * @var string
     * @ORM\Column(name="priority", type="string")
     */
    private $priority = "";

    /**
     * @var \DateTime
     * @ORM\Column(name="due_date", type="datetime")
     */
    private $due_date;

    /**
     * @var \DateTime
     * @ORM\Column(name="create_date", type="datetime")
     */
    private $create_date;

    /**
     * @return mixed
     */
    public function getId()
    {
        return $this->id;
    }

    /**
     * @param mixed $id
     */
    public function setId($id): void
    {
        $this->id = $id;
    }

    /**
     * @return string
     */
    public function getName(): string
    {
        return $this->name;
    }

    /**
     * @param string $name
     */
    public function setName(string $name): void
    {
        $this->name = $name;
    }

    /**
     * @return string
     */
    public function getCategory(): string
    {
        return $this->category;
    }

    /**
     * @param string $category
     */
    public function setCategory(string $category): void
    {
        $this->category = $category;
    }

    /**
     * @return string
     */
    public function getDescription(): string
    {
        return $this->description;
    }

    /**
     * @param string $description
     */
    public function setDescription(string $description): void
    {
        $this->description = $description;
    }


    /**
     * @return string
     */
    public function getPriority(): string
    {
        return $this->priority;
    }

    /**
     * @param string $priority
     */
    public function setPriority(string $priority): void
    {
        $this->priority = $priority;
    }

    /**
     * @return \DateTime
     */
    public function getDueDate(): \DateTime
    {
        return $this->due_date;
    }

    /**
     * @param \DateTime $due_date
     */
    public function setDueDate(\DateTime $due_date): void
    {
        $this->due_date = $due_date;
    }

    /**
     * @return \DateTime
     */
    public function getCreateDate(): \DateTime
    {
        return $this->create_date;
    }

    /**
     * @param \DateTime $create_date
     */
    public function setCreateDate(\DateTime $create_date): void
    {
        $this->create_date = $create_date;
    }

}

src/Controller/TodoController.php
<?php

namespace App\Controller;

use App\Entity\Todo;
use Symfony\Component\Form\Extension\Core\Type\SubmitType;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Bundle\FrameworkBundle\Controller\Controller;
use Symfony\Component\Routing\Annotation\Route;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\Form\Extension\Core\Type\TextType;
use Symfony\Component\Form\Extension\Core\Type\TextareaType;
use Symfony\Component\Form\Extension\Core\Type\DateTimeType;
use Symfony\Component\Form\Extension\Core\Type\ChoiceType;



class TodoController extends Controller
{
    /**
     * Matches / exactly
     * @Route("/", name="home")
     */
    public function default(){
        return $this->list();
    }

    /**
     * @Route("/todo", name="index")
     */
    public function list(){

        $todos = $this->getDoctrine()->getRepository(Todo::class)->findAll();

        return $this->render('todo/index.html.twig', array('page' => "Home", 'todos' => $todos));
    }

    /**
     * @Route("/todo/create", name="create")
     */
    public function create(Request $request){
       $todo = new Todo();

       $todo->setDueDate(new \DateTime());
       $todo->setCreateDate(new \DateTime());

        $form = $this->createFormBuilder($todo)
            ->add('name', TextType::class, array('attr' => array('class' => 'form-control', 'style' => 'margin-bottom: 15px')))
            ->add('category', TextType::class, array('attr' => array('class' => 'form-control', 'style' => 'margin-bottom: 15px')))
            ->add('description', TextareaType::class, array('attr' => array('class' => 'form-control', 'style' => 'margin-bottom: 15px')))
            ->add('priority', ChoiceType::class, array('choices' => array('Low' => 'Low', 'Normal' => 'Normal', 'High' => 'High'), 'attr' => array('class' => 'form-control', 'style' => 'margin-bottom: 15px')))
            ->add('due_date', DateTimeType::class, array('attr' => array('class' => 'form-control', 'style' => 'margin-bottom: 15px')))
            ->add('save', SubmitType::class, array('label' => 'Create Todo', 'attr' => array('class' => 'btn btn-primary float-right', 'style' => 'margin-bottom: 15px; margin-left:10px;')))
            ->getForm();

        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()){
            $todo = $form->getData();
            $em = $this->getDoctrine()->getManager();
            $em->persist($todo);
            $em->flush();
            $this->addFlash('notice', 'Todo Added');
            return $this->redirectToRoute('index');
        }

        return $this->render('todo/create.html.twig', array('page' => "create", 'form' => $form->createView()));
    }

    /**
     * @Route("/todo/edit/{id}", name="edit", requirements={"id"="\d+"})
     */
    public function edit($id, Request $request){
        $todo = $this->getDoctrine()->getRepository(Todo::class)->find($id);

        $form = $this->createFormBuilder($todo)
            ->add('name', TextType::class, array('attr' => array('class' => 'form-control', 'style' => 'margin-bottom: 15px')))
            ->add('category', TextType::class, array('attr' => array('class' => 'form-control', 'style' => 'margin-bottom: 15px')))
            ->add('description', TextareaType::class, array('attr' => array('class' => 'form-control', 'style' => 'margin-bottom: 15px')))
            ->add('priority', ChoiceType::class, array('choices' => array('Low' => 'Low', 'Normal' => 'Normal', 'High' => 'High'), 'attr' => array('class' => 'form-control', 'style' => 'margin-bottom: 15px')))
            ->add('due_date', DateTimeType::class, array('attr' => array('class' => 'form-control', 'style' => 'margin-bottom: 15px')))
            ->add('save', SubmitType::class, array('label' => 'Update Todo', 'attr' => array('class' => 'btn btn-primary', 'style' => 'margin-bottom: 15px')))
            ->getForm();

        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()){
            $todo = $form->getData();
            $em = $this->getDoctrine()->getManager();
            $em->getRepository(Todo::class);
            $em->flush();
            $this->addFlash('notice', 'Todo Updated');
            return $this->redirectToRoute('index');
        }

        return $this->render('todo/edit.html.twig', array('page' => "edit", 'form' => $form->createView()));
    }

    /**
     * Matches /delete exactly
     * @Route("/todo/delete/{id}", name="delete", requirements={"id"="\d+"})
     */
    public function delete($id){
        $todo = $this->getDoctrine()->getRepository(Todo::class)->find($id);
        $em = $this->getDoctrine()->getManager();
        $em->getRepository(Todo::class);
        $em->remove($todo);
        $em->flush();
        $this->addFlash('notice', 'Todo Updated');
        return $this->redirectToRoute('index');
    }

    /**
     * Matches /details exactly
     * @Route("/todo/details/{id}", name="details", requirements={"id"="\d+"})
     */
    public function details($id){

        $todo = $this->getDoctrine()->getRepository(Todo::class)->find($id);

        return $this->render('todo/details.html.twig', array('page' => "details", 'todo' => $todo));
    }

}

templates/todo/create.html.twig
{% extends 'base.html.twig' %}
{% block body %}
    <h2 class="page-header" style="margin-top:20px; margin-bottom:20px;">{{ page }}</h2>
    {{ form_start(form) }}
    {{ form_widget(form) }}
    {{ form_end(form) }}

    <div class="clearfix">
        <a href="/" class="btn btn-primary float-right" style="margin-bottom: 20px;">Cancel</a>
    </div>
{% endblock %}

templates/todo/details.html.twig
{% extends 'base.html.twig' %}
{% block body %}

    <h2 class="page-header" style="margin-top:20px;marin-bottom:20px;">{{ todo.name }}</h2>

    <ul class="list-group">
        <li class="list-group-item">Category: {{ todo.category }}</li>
        <li class="list-group-item">Priority: {{ todo.priority }}</li>
        <li class="list-group-item">Due Date: {{  todo.dueDate | date('d/m/Y H:i:s') }}</li>
        <li class="list-group-item">Created: {{  todo.createDate | date('d/m/Y H:i:s') }}</li>
    </ul>

    <p>{{ todo.description }}</p>

    <a class="btn btn-primary" style="margin-top: 20px; margin-bottom: 20px;" href="/">Back to TODOs</a>
{% endblock %}

templates/todo/edit.html.twig
{% extends 'base.html.twig' %}
{% block body %}
    <h2 class="page-header" style="margin-top:20px; margin-bottom:20px;">{{ page }}</h2>
    {{ form_start(form) }}
    {{ form_widget(form) }}
    {{ form_end(form) }}
{% endblock %}

templates/todo/index.html.twig
{% extends 'base.html.twig' %}
{% block body %}
    <h2 class="page-header" style="margin-top:20px; margin-bottom:20px;">Latest Todo</h2>
    <table class="table table-striped" style="margin-top: 20px;">
    <thead>
        <tr>
        <th scope="col">#</th>
        <th scope="col">Todo</th>
        <th scope="col">Due Date</th>
        <th scope="col"></th>
        </tr>
    </thead>
    <tbody>

        {% for todo in todos %}
        <tr>
        <th scope="row">{{ todo.id }}</th>
        <td>{{ todo.name }}</td>
        <td>{{ todo.dueDate | date('d/m/Y H:i:s') }}</td>
        <td>
            <a href="/todo/details/{{ todo.id }}" class="btn btn-success">view</a>
            <a href="/todo/edit/{{ todo.id }}" class="btn btn-primary">edit</a>
            <a href="/todo/delete/{{ todo.id }}" class="btn btn-danger">delete</a>
        </td>
        </tr>
        {% endfor %}
    </tbody>
    </table>
    <div class="clearfix">
        <a href="/todo/create" class="btn btn-primary float-right">Add ToDo</a>
    </div>
{% endblock %}