src/Entity/Task.php
<?php

namespace App\Entity;

use Doctrine\ORM\Mapping as ORM;

/**
 * @ORM\Entity(repositoryClass="App\Repository\TaskRepository")
 */
class Task
{
    /**
     * @ORM\Id
     * @ORM\GeneratedValue
     * @ORM\Column(type="integer")
     */
    private $id;

    // add your own fields

    /**
     * @var String
     * @ORM\Column(name="title", type="string")
     *
     */
    private $title = "";

    /**
     * @var String
     * @ORM\Column(name="description", type="string")
     */
    private $description = "";

    /**
     * @var String
     * @ORM\Column(name="time_spent", type="integer")
     */
    private $time_spent = 0;

    /**
     * @return mixed
     */
    public function getId()
    {
        return $this->id;
    }

    /**
     * @param mixed $id
     */
    public function setId($id): void
    {
        $this->id = $id;
    }

    /**
     * @return String
     */
    public function getTitle(): String
    {
        return $this->title;
    }

    /**
     * @param String $title
     */
    public function setTitle(String $title): void
    {
        $this->title = $title;
    }

    /**
     * @return String
     */
    public function getDescription(): String
    {
        return $this->description;
    }

    /**
     * @param String $description
     */
    public function setDescription(String $description): void
    {
        $this->description = $description;
    }

    /**
     * @return String
     */
    public function getTimeSpent(): String
    {
        return $this->time_spent;
    }

    /**
     * @param String $time_spent
     */
    public function setTimeSpent(String $time_spent): void
    {
        $this->time_spent = $time_spent;
    }

}

src/Controller/TaskController.php
<?php
/**
 * Created by PhpStorm.
 * User: higor.bocutti
 * Date: 11/01/2018
 * Time: 12:03
 */

namespace App\Controller;

use App\Entity\Task;
use Symfony\Bundle\FrameworkBundle\Controller\Controller;
use Symfony\Component\Form\Extension\Core\Type\IntegerType;
use Symfony\Component\Form\Extension\Core\Type\SubmitType;
use Symfony\Component\Form\Extension\Core\Type\TextType;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;
use Symfony\Component\HttpFoundation\Request;

class TaskController extends Controller
{

    /**
     * @Route("/task", name="task")
     */
    public function default(){
        $tasks = $this->getDoctrine()->getRepository(Task::class)->findAll();

        return $this->render('tasks/index.html.twig', array('page' => 'Tasks', 'tasks' => $tasks));
    }

    /**
     * @Route("/task/create", name="Create Tasks")
     */
    public function createTask(Request $request){
        $task = new Task();
        $form = $this->createFormBuilder($task)
            ->add('title', TextType::class, array('attr' => array('class' => 'form-control', 'style' => 'margin-bottom: 15px')))
            ->add('description', TextType::class, array('attr' => array('class' => 'form-control', 'style' => 'margin-bottom: 15px')))
            ->add('time_spent', IntegerType::class, array('attr' => array('class' => 'form-control', 'style' => 'margin-bottom: 15px')))
            ->add('save', SubmitType::class, array('label' => 'Add Task', 'attr' => array('class' => 'btn btn-primary', 'style' => 'margin-bottom: 15px')))
        ->getForm();

        $form->handleRequest($request);

        if($form->isSubmitted() && $form->isValid()){
            $task = $form->getData();
            $em = $this->getDoctrine()->getManager();
            $em->persist($task);
            $em->flush();
            $this->addFlash('notice', 'Task Added');
            return $this->redirectToRoute('task');
        }

        return $this->render('tasks/taskForm.html.twig', array('page' => 'Create Task', 'form' => $form->createView()));
    }

    /**
     * Matches /task/edit exactly
     * @Route("/task/edit/{id}", name="Edit Task", requirements={"id"="\d+"})
     */
    public function editTask($id, Request $request){
        $task = $this->getDoctrine()->getRepository(Task::class)->find($id);

        $form = $this->createFormBuilder($task)
            ->add('title', TextType::class, array('attr' => array('class' => 'form-control', 'style' => 'margin-bottom: 15px')))
            ->add('description', TextType::class, array('attr' => array('class' => 'form-control', 'style' => 'margin-bottom: 15px')))
            ->add('time_spent', IntegerType::class, array('attr' => array('class' => 'form-control', 'style' => 'margin-bottom: 15px')))
            ->add('save', SubmitType::class, array('label' => 'Edit Task', 'attr' => array('class' => 'btn btn-primary', 'style' => 'margin-bottom: 15px')))
            ->getForm();

        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()){
            $em = $this->getDoctrine()->getManager();
            $em->getRepository(Task::class);
            $em->flush();
            $this->addFlash('notice', 'Todo Updated');
            return $this->redirectToRoute('task');
        }

        return $this->render('tasks/taskForm.html.twig', array('page' => 'Edit Task', 'form' => $form->createView()));
    }

    /**
     * Matches /task/delete exactly
     * @Route("/task/delete/{id}", name="Delete Tasks", requirements={"id"="\d+"})
     */
    public function deleteTask($id, Request $request){
        $task = $this->getDoctrine()->getRepository(Task::class)->find($id);
        $em = $this->getDoctrine()->getManager();
        $em->getRepository(Task::class);
        $em->remove($task);
        $em->flush();

        $this->addFlash('notice', 'Task Deleted');
        return $this->redirectToRoute('task');
    }
    
}

templates/tasks/index.html.twig
{% extends 'base.html.twig' %}
{% block body %}
    <h2 class="page-header" style="margin-top:20px; margin-bottom:20px;">{{ page }}</h2>
    <table class="table table-striped" style="margin-top: 20px;">
        <thead>
        <tr>
            <th scope="col">#</th>
            <th scope="col">Title</th>
            <th scope="col">Description</th>
            <th scope="col">Time spent</th>
            <th scope="col"></th>
        </tr>
        </thead>
        <tbody>

        {% set totalSpent = 0 %}
        {% set goalTime = 480 %}
        {% for task in tasks %}

            <tr>
                <th scope="row">{{ task.id }}</th>
                <td>{{ task.title }}</td>
                <td>{{ task.description }}</td>
                <td>{{ (task.timeSpent > 1)? task.timeSpent ~ ' minutes' : task.timeSpent ~ ' minute' }} </td>
                <td>
                    <a href="/task/edit/{{ task.id }}" class="btn btn-primary">edit</a>
                    <a href="/task/delete/{{ task.id }}" class="btn btn-danger">delete</a>
                </td>
            </tr>

            {% set totalSpent = totalSpent + task.timeSpent %}
        {% endfor %}


        </tbody>
    </table>

    <div class="clearfix">
        <span class="float-right">Time Spent Total: {{ ( totalSpent > 1 )? totalSpent ~ ' minutes' : totalSpent ~ ' minute' }}</span>
    </div>
    <div class="clearfix">
        {% set timeLeft = goalTime - totalSpent %}
        <span class="float-right">Time Left: {{ (timeLeft > 1)? timeLeft ~ ' minutes': timeLeft ~ ' minute' }}</span>
    </div>


    <div class="col-sm-12" style="margin-top:20px; margin-bottom:20px;">
        <a href="/task/create" class="btn btn-primary">New Task</a>
    </div>
{% endblock %}

templates/tasks/taskForm.html.twig
{% extends 'base.html.twig' %}
{% block body %}
    <h2 class="page-header" style="margin-top:20px; margin-bottom:20px;">{{ page }}</h2>
    {{ form_start(form) }}
    {{ form_widget(form) }}
    {{ form_end(form) }}
    <div class="clearfix">
        <a href="/task" class="btn btn-secondary float-right"> Close</a>
    </div>
{% endblock %}